### ISSUE TITLE
Allow /lock/:lock PUT to block until lock claimed

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/locker#1]
@geofffranks Currently the client to locker must manager the wait-retry-loop if unsuccessful claiming a lock, e.g. https://github.com/cloudfoundry-community/locker-resource/blob/master/assets/out#L47-L54

Perhaps a caller to `curl lock.me/lock/my-thing -X PUT -d '{"type": "block-til-unlocked"}'` would all block/long-poll until the locker server returns to them that they have the lock. This would simplify simple client scripts who would only have to call a blocking `curl lock.me/lock/my-thing -X PUT` and the next line would be guaranteed to have the lock.

**Comment by geofffranks** [comment]
I didn't want to do that due to the varying intermediary devices that may have HTTP timeouts breaking the connection. Polling/retrying seemed like a more reliable/simpler approach. If the long-poll can be done safely + reliably, I'm not against it though.
